apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-volumes
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  serviceName: svc-statefulset-volume
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx-container
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
        volumeMounts:
        - name: pvc
          mountPath: /usr/share/nginx/html
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: mypvc
